Support for assuming role for schema registry operations when using kafka connect
awslabs/aws-glue-schema-registry pull request #209
Opened 2022-08-17 19:27 UTC by liambuchanan

### Context

* I imagine it's relatively common to share a schema registry among multiple AWS accounts within an organization necessitating cross account access to schema registries.
* Glue Registry does not support resource permissions so cross account have to be used to access schema registries.
* There's currently no way to assume cross account roles when using `AWSKafkaAvroConverter`

### Changes

This PR adds two new configuration parameters used in `AWSKafkaAvroConverter`:
* `sts.roleArn` provides a role ARN to be used when using an AWS glue schema registry
* `sts.roleSessionName` provides a role session name to be used when using an AWS glue schema registry

When both parameters are provided the `AWSKafkaAvroConverter` constructs an `StsAssumeRoleCredentialsProvider` to be used when accessing the registry schema.

2022-11-09 19:06 UTC, mohitpali requested changes

2022-11-09 19:06 UTC, mohitpali commented on avro-kafkaconnect-converter/src/main/java/com/amazonaws/services/schemaregistry/kafkaconnect/AWSKafkaAvroConverter.java
> +    private static final String STS_ROLE_ARN = "sts.roleArn";
Could you please replace the naming from camel casing to dotted.
e.g. "sts.role.arn"

We have learned that some of the Docker conversions assume Kafka standard of having no camel casing. Some external Docker images provide configurations as ALL CAPS with UNDERSCORES and then translate _ to . and CAPS to small.

2022-11-09 19:06 UTC, mohitpali commented on avro-kafkaconnect-converter/src/main/java/com/amazonaws/services/schemaregistry/kafkaconnect/AWSKafkaAvroConverter.java
> +        final String roleSessionName = configs.get(STS_ROLE_SESSION_NAME) == null
If session name is not provided, should be default to a default session name ?

2022-11-09 19:08 UTC, mohitpali commented
Thanks for this PR ! And I am sorry for getting to it late. I have added some comments. It would be great if you could address and resubmit.

2023-02-13 11:25 UTC, austiine04 commented
Hello, this PR is perfect for a use case am working on, would love to see it merged in and am happy to work on the requested changes for that, but first i have a question.

Would it better to push the fix to this branch/PR or should i create an entirely new branches with all the changes of this PR plus the feedback?

What's the recommended approach here?

2023-03-07 16:45 UTC, liambuchanan commented
@mohitpali updated to use dot notation for config params and added a default value for the session name

2023-03-13 06:45 UTC, insani4c commented
Hi @mohitpali ,

This plugin does exactly what is needed for cross-account access to an AWS Glue schema registry.
Could this review please get picked up and merged? I've tested this PR and it works just fine.

Thanks

2023-03-13 17:00 UTC, mohitpali requested changes

2023-03-13 17:03 UTC, mohitpali commented on avro-kafkaconnect-converter/src/main/java/com/amazonaws/services/schemaregistry/kafkaconnect/AWSKafkaAvroConverter.java
> +    private static final String STS_ROLE_SESSION_NAME_DEFAULT = "schema-registry-kafkaconnect-converter";
> Hello, this PR is perfect for a use case am working on, would love to see it merged in and am happy to work on the requested changes for that, but first i have a question.

> Would it better to push the fix to this branch/PR or should i create an entirely new branches with all the changes of this PR plus the feedback?

> What's the recommended approach here?


You can choose whichever approach works for you. A PR that is from a branch on your fork can be merged directly into master with a PR.

2023-04-06 12:38 UTC, closed without merging

2024-12-18 20:26 UTC, dafuallah96 commented
Hi, would like to know the reason this PR was closed? It would be great to have this feature as this is something thing that can be greatly used for my use case

2024-12-18 20:27 UTC, dafuallah96 commented
Hi, would like to know the reason this PR was closed? It would be great to have this feature as this is something thing that can be greatly used for my use case
cc: @liambuchanan @mohitpali

2025-01-29 20:21 UTC, liambuchanan commented
@dafuallah96 I only closed as I'm no longer using the schema registry and it appeared that it was going to be a bit of a slog to get this merged. Feel free to pick up where I left off.